/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scanenvy;

import java.awt.Dimension;
import static java.awt.Toolkit.getDefaultToolkit;
import java.util.ArrayList;

/**
 *
 * @author Kirjsten
 */
public class votingGUI extends javax.swing.JFrame {
    
    int number1=0;
    String commenttext1 = "comment 1", commenttext2 = "comment 2", commenttext3 = "comment 3", commmenttext4 = "comment 4";
    private ArrayList<Comment> commentList = new ArrayList<Comment>();
    
    

    /**
     * Creates new form votingGUI
     */
    public votingGUI() {
        initComponents();
        Dimension screenSize = getDefaultToolkit().getScreenSize();
        setBounds(0,40,screenSize.width, screenSize.height -40);
        setPreferredSize(new Dimension(screenSize.width, screenSize.height -40));
        Comment comment = new Comment(number1, commenttext1);
        commentList.add(comment);
        Comment comment1 = new Comment(number1, commenttext2);
        commentList.add(comment1);
        Comment comment2 = new Comment(number1, commenttext3);
        commentList.add(comment2);
        Comment comment3 = new Comment(number1, commmenttext4);
        commentList.add(comment3);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        votingGUIPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        likes1 = new javax.swing.JLabel();
        likes3 = new javax.swing.JLabel();
        likes4 = new javax.swing.JLabel();
        likes2 = new javax.swing.JLabel();
        loadingSystem = new javax.swing.JLabel();
        up1 = new javax.swing.JButton();
        down1 = new javax.swing.JButton();
        up2 = new javax.swing.JButton();
        down2 = new javax.swing.JButton();
        up3 = new javax.swing.JButton();
        down3 = new javax.swing.JButton();
        up4 = new javax.swing.JButton();
        down4 = new javax.swing.JButton();
        comment2 = new javax.swing.JLabel();
        comment3 = new javax.swing.JLabel();
        comment4 = new javax.swing.JLabel();
        comment1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        votingGUIPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comment");

        likes1.setBackground(new java.awt.Color(255, 255, 255));
        likes1.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        likes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        likes1.setText("#");
        likes1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        likes3.setBackground(new java.awt.Color(255, 255, 255));
        likes3.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        likes3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        likes3.setText("#");
        likes3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        likes4.setBackground(new java.awt.Color(255, 255, 255));
        likes4.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        likes4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        likes4.setText("#");
        likes4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        likes2.setBackground(new java.awt.Color(255, 255, 255));
        likes2.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        likes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        likes2.setText("#");
        likes2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        loadingSystem.setBackground(new java.awt.Color(255, 255, 255));
        loadingSystem.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        loadingSystem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadingSystem.setText(" ");
        loadingSystem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        up1.setBackground(new java.awt.Color(255, 255, 255));
        up1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        up1.setText("^");
        up1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        up1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up1MouseClicked(evt);
            }
        });

        down1.setBackground(new java.awt.Color(255, 255, 255));
        down1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        down1.setText("v");
        down1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        down1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                down1MouseClicked(evt);
            }
        });

        up2.setBackground(new java.awt.Color(255, 255, 255));
        up2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        up2.setText("^");
        up2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        up2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up2MouseClicked(evt);
            }
        });

        down2.setBackground(new java.awt.Color(255, 255, 255));
        down2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        down2.setText("v");
        down2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        down2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                down2MouseClicked(evt);
            }
        });

        up3.setBackground(new java.awt.Color(255, 255, 255));
        up3.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        up3.setText("^");
        up3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        up3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up3MouseClicked(evt);
            }
        });

        down3.setBackground(new java.awt.Color(255, 255, 255));
        down3.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        down3.setText("v");
        down3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        down3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                down3MouseClicked(evt);
            }
        });

        up4.setBackground(new java.awt.Color(255, 255, 255));
        up4.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        up4.setText("^");
        up4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        up4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up4MouseClicked(evt);
            }
        });

        down4.setBackground(new java.awt.Color(255, 255, 255));
        down4.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        down4.setText("v");
        down4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        down4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                down4MouseClicked(evt);
            }
        });

        comment2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        comment2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comment2.setText("Comment 2");
        comment2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comment3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        comment3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comment3.setText("Comment 3");
        comment3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comment4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        comment4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comment4.setText("Comment 4");
        comment4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comment1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        comment1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comment1.setText("Comment 1");
        comment1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout votingGUIPanelLayout = new javax.swing.GroupLayout(votingGUIPanel);
        votingGUIPanel.setLayout(votingGUIPanelLayout);
        votingGUIPanelLayout.setHorizontalGroup(
            votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, votingGUIPanelLayout.createSequentialGroup()
                .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(votingGUIPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(votingGUIPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(up1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(down1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(up2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(down2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(up3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(down3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(up4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(down4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(likes3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(likes2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(likes1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(likes4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comment3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(comment4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comment2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comment1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadingSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        votingGUIPanelLayout.setVerticalGroup(
            votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(votingGUIPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(votingGUIPanelLayout.createSequentialGroup()
                        .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(votingGUIPanelLayout.createSequentialGroup()
                                .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(votingGUIPanelLayout.createSequentialGroup()
                                        .addComponent(likes1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(votingGUIPanelLayout.createSequentialGroup()
                                        .addComponent(comment1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(likes2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comment2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(votingGUIPanelLayout.createSequentialGroup()
                                .addComponent(up1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(down1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(up2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(down2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(likes3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comment3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(votingGUIPanelLayout.createSequentialGroup()
                                .addComponent(up3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(down3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(votingGUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(votingGUIPanelLayout.createSequentialGroup()
                                .addComponent(up4)
                                .addGap(18, 18, 18)
                                .addComponent(down4))
                            .addComponent(likes4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comment4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(loadingSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(votingGUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(votingGUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up1MouseClicked
        sort();
        commentList.get(4).setLikes(commentList.get(4).getLikes()+1);
        likes1.setText(Integer.toString(commentList.get(4).getLikes()));
    }//GEN-LAST:event_up1MouseClicked

    private void down1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_down1MouseClicked
        sort();
        commentList.get(4).setLikes(commentList.get(4).getLikes()-1);
        likes1.setText(Integer.toString(commentList.get(4).getLikes()));
    }//GEN-LAST:event_down1MouseClicked

    private void up2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up2MouseClicked
        sort();
        commentList.get(3).setLikes(commentList.get(3).getLikes()+1);
        likes2.setText(Integer.toString(commentList.get(3).getLikes()));
    }//GEN-LAST:event_up2MouseClicked

    private void down2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_down2MouseClicked
        sort();
        commentList.get(3).setLikes(commentList.get(3).getLikes()-1);
        likes2.setText(Integer.toString(commentList.get(3).getLikes()));
    }//GEN-LAST:event_down2MouseClicked

    private void up3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up3MouseClicked
        sort();
        commentList.get(2).setLikes(commentList.get(2).getLikes()+1);
        likes3.setText(Integer.toString(commentList.get(2).getLikes()));
    }//GEN-LAST:event_up3MouseClicked

    private void down3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_down3MouseClicked
        sort();
        commentList.get(2).setLikes(commentList.get(2).getLikes()-1);
        likes3.setText(Integer.toString(commentList.get(2).getLikes()));
    }//GEN-LAST:event_down3MouseClicked

    private void up4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up4MouseClicked
        sort();
        commentList.get(1).setLikes(commentList.get(1).getLikes()+1);
        likes4.setText(Integer.toString(commentList.get(1).getLikes()));
    }//GEN-LAST:event_up4MouseClicked

    private void down4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_down4MouseClicked
        sort();
        commentList.get(1).setLikes(commentList.get(1).getLikes()-1);
        likes4.setText(Integer.toString(commentList.get(1).getLikes()));
    }//GEN-LAST:event_down4MouseClicked

    
    public void sort()
    {
        ArrayList<Comment> tempList = new ArrayList<Comment>();
        boolean sorted = false;
        int max = 000;
        Comment commentMax = commentList.get(1);
        Comment commentMin = commentList.get(1);
        int min = 999;
        for(int i = 0; i <=4; i++)
        {
            
            {
                if(commentList.get(i).getLikes()>= max)
                {
                    max = commentList.get(i).getLikes();
                    commentMax = commentList.get(i);
                }
                
                if(commentList.get(i).getLikes()<= min)
                {
                    min = commentList.get(i).getLikes();
                    commentMin = commentList.get(i);
                }  
            }
            tempList.add(1, commentMin);
            tempList.add(4, commentMax);
            if(!(min == commentList.get(i).getLikes()) && !(commentMin.getComment().equalsIgnoreCase(commentList.get(i).getComment())))
            {
                if(!(max == commentList.get(i).getLikes()) && !(commentMax.getComment().equalsIgnoreCase(commentList.get(i).getComment())))
                {
                    tempList.add(commentList.get(i));
                    
                }
            }
        }
        commentList = tempList;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(votingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(votingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(votingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(votingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new votingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comment1;
    private javax.swing.JLabel comment2;
    private javax.swing.JLabel comment3;
    private javax.swing.JLabel comment4;
    private javax.swing.JButton down1;
    private javax.swing.JButton down2;
    private javax.swing.JButton down3;
    private javax.swing.JButton down4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel likes1;
    private javax.swing.JLabel likes2;
    private javax.swing.JLabel likes3;
    private javax.swing.JLabel likes4;
    private javax.swing.JLabel loadingSystem;
    private javax.swing.JButton up1;
    private javax.swing.JButton up2;
    private javax.swing.JButton up3;
    private javax.swing.JButton up4;
    private javax.swing.JPanel votingGUIPanel;
    // End of variables declaration//GEN-END:variables
}
