/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scanenvy.editable;
import java.util.ArrayList;
import java.awt.Dimension;
import static java.awt.Toolkit.getDefaultToolkit;
/**
 *
 * @author Kirjsten
 */
public class Display extends javax.swing.JFrame {
    private int upc = 0, recycleNew=0;
    private ArrayList<UPCObject> upcList = new ArrayList<UPCObject>();
    
    /**
     * Creates new form Display
     */
    public Display() {
      
        initComponents();
        Dimension screenSize = getDefaultToolkit().getScreenSize();
        setBounds(0,40,screenSize.width, screenSize.height -40);
        setPreferredSize(new Dimension(screenSize.width, screenSize.height -40));
        scanEnvyLogo.setBounds(this.getWidth()-(scanEnvyLogo.getWidth()/2), scanEnvyLogo.getY(), scanEnvyLogo.getWidth(), scanEnvyLogo.getHeight());
        //recycleEditCombo.add("Not Recyclable", new textfeild);
        //recycleEditCombo.add("Plastic Code 1-6", this);
        //recycleEditCombo.add("Plastic Code 7", this);
        //recycleEditCombo.add("Metal", this);
        //recycleEditCombo.add("Paper/Cardboard", this);
        //recycleEditCombo.add("Glass", this);
        //recycleEditCombo.add("Batteries/Bulbs", this);
        //recycleEditCombo.add("Electronics", this);
        
        //make screen size -40 of fulscreen Ask thomas
        displayEdit.setVisible(false);
        displayInfo.setVisible(false);
        UPCObject upctemp = new UPCObject(123456, "Cinnamon", "Stripers Co.", 0);
        upcList.add(upctemp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        recycleEditCombo = new javax.swing.JComboBox();
        homePage = new javax.swing.JPanel();
        homePageLabel = new javax.swing.JLabel();
        upcText = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        displayEdit = new javax.swing.JPanel();
        ManufactEditText = new javax.swing.JTextField();
        recycleEditText = new javax.swing.JTextField();
        itemEditText = new javax.swing.JTextField();
        enterEditButton = new javax.swing.JButton();
        userInfoPrompt1 = new javax.swing.JLabel();
        userInfoPromt2 = new javax.swing.JLabel();
        helpEditButton = new javax.swing.JButton();
        displayInfo = new javax.swing.JPanel();
        cpuCodeLabel = new javax.swing.JLabel();
        itemLabel = new javax.swing.JLabel();
        manufactLabel = new javax.swing.JLabel();
        recycleTypeLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        scanEnvyLogo = new javax.swing.JLabel();

        recycleEditCombo.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        recycleEditCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        recycleEditCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        recycleEditCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycleEditComboActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homePage.setBackground(new java.awt.Color(255, 255, 255));
        homePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePageLabel.setBackground(new java.awt.Color(255, 255, 255));
        homePageLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        homePageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appPackage/scanENVYimage2 copy.png"))); // NOI18N
        homePage.add(homePageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 74, -1, 120));

        upcText.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        upcText.setForeground(new java.awt.Color(102, 102, 102));
        upcText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        upcText.setText("Enter UPC");
        upcText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        homePage.add(upcText, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 262, 196, 34));

        okButton.setBackground(new java.awt.Color(255, 255, 255));
        okButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        okButton.setText("OK");
        okButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });
        homePage.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 261, 44, 34));

        displayEdit.setBackground(new java.awt.Color(255, 255, 255));
        displayEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManufactEditText.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        ManufactEditText.setForeground(new java.awt.Color(153, 153, 153));
        ManufactEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ManufactEditText.setText("Manufacturor");
        ManufactEditText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayEdit.add(ManufactEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 267, 239, 52));

        recycleEditText.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        recycleEditText.setForeground(new java.awt.Color(153, 153, 153));
        recycleEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recycleEditText.setText("Recyclable Number");
        recycleEditText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayEdit.add(recycleEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 325, 239, 52));

        itemEditText.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        itemEditText.setForeground(new java.awt.Color(153, 153, 153));
        itemEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemEditText.setText("Item Name");
        itemEditText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayEdit.add(itemEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 209, 239, 52));

        enterEditButton.setBackground(new java.awt.Color(255, 255, 255));
        enterEditButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        enterEditButton.setText("Enter");
        enterEditButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enterEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterEditButtonMouseClicked(evt);
            }
        });
        displayEdit.add(enterEditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 395, 173, 38));

        userInfoPrompt1.setBackground(new java.awt.Color(255, 255, 255));
        userInfoPrompt1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        userInfoPrompt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userInfoPrompt1.setText("You are the first to scan this item!");
        displayEdit.add(userInfoPrompt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 102, 261, 47));

        userInfoPromt2.setBackground(new java.awt.Color(255, 255, 255));
        userInfoPromt2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        userInfoPromt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userInfoPromt2.setText("Please Enter Item Information");
        displayEdit.add(userInfoPromt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 155, -1, 43));

        helpEditButton.setBackground(new java.awt.Color(255, 255, 255));
        helpEditButton.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        helpEditButton.setText("?");
        helpEditButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        helpEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpEditButtonMouseClicked(evt);
            }
        });
        displayEdit.add(helpEditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 395, 56, 38));

        displayInfo.setBackground(new java.awt.Color(255, 255, 255));
        displayInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cpuCodeLabel.setBackground(new java.awt.Color(255, 255, 255));
        cpuCodeLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        cpuCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cpuCodeLabel.setText("UPC CODE");
        cpuCodeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayInfo.add(cpuCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 185, 45));

        itemLabel.setBackground(new java.awt.Color(255, 255, 255));
        itemLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        itemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemLabel.setText("Item");
        itemLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayInfo.add(itemLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 185, 49));

        manufactLabel.setBackground(new java.awt.Color(255, 255, 255));
        manufactLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        manufactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manufactLabel.setText("Manufact");
        manufactLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayInfo.add(manufactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 185, 42));

        recycleTypeLabel.setBackground(new java.awt.Color(255, 255, 255));
        recycleTypeLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        recycleTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recycleTypeLabel.setText("Default");
        recycleTypeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayInfo.add(recycleTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 185, 42));

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        editButton.setText("Edit");
        editButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });
        displayInfo.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 104, 40));

        doneButton.setBackground(new java.awt.Color(255, 255, 255));
        doneButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        doneButton.setText("Done");
        doneButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneButtonMouseClicked(evt);
            }
        });
        displayInfo.add(doneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 104, 35));

        scanEnvyLogo.setBackground(new java.awt.Color(255, 255, 255));
        scanEnvyLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scanEnvyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appPackage/scanENVYimage2 copy.png"))); // NOI18N
        displayInfo.add(scanEnvyLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 428, 105));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homePage, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(displayEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(displayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homePage, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(displayEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(displayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        
                          

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {                                      
        //read from upcText
        upc = Integer.parseInt(upcText.getText());
        int upcGet;
        boolean found = false;
        for(int i = 0; i < upcList.size(); i++)
        { 
            upcGet = upcList.get(i).getUPC();
            if(upcGet==upc)
            {
                //change panel to display upc information
                homePage.setVisible(false);
                cpuCodeLabel.setText(Integer.toString(upcList.get(i).getUPC()));
                itemLabel.setText(upcList.get(i).getItem());
                manufactLabel.setText(upcList.get(i).getManufact());
                
                int recycle = upcList.get(i).getRecycleType();
                switch(recycle)
                {
                    case 1:     
                    case 2:
                    case 3:
                    case 4:
                    case 5:
                    case 6:
                        recycleTypeLabel.setText("A plastic recyclable.");
                        break;
                    case 8:
                        recycleTypeLabel.setText("A metal recycleable");
                        break;
                    case 9:
                        recycleTypeLabel.setText("A paper or cardboard recycable");
                        break;
                    case 10:
                        recycleTypeLabel.setText("A glass recyclable");
                        break;
                    case 11:
                        recycleTypeLabel.setText("A battery or bulb recyclable. Special Recycle Needed");
                        break;
                    case 12:
                        recycleTypeLabel.setText("An electronic recyclable product.Special Recycle Needed");
                        break;
                        
                            default:
                                recycleTypeLabel.setText("Not Recyclable");
                                break;
                }
                displayInfo.setVisible(true);
                found = true;
                
            }
        }       
        
        if(!found)
        {
            //change panel to create up
            homePage.setVisible(false);
            displayEdit.setVisible(true);
        }
       
    }                                                                           

    private void enterEditButtonMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        String itemNew = itemEditText.getText();
        String manufactNew = ManufactEditText.getText();
        recycleNew = Integer.parseInt(recycleEditText.getText());
        UPCObject upcTemp = new UPCObject(upc, itemNew, manufactNew, recycleNew);
        upcList.add(upcTemp);
        displayEdit.setVisible(false);
        homePage.setVisible(true);
    }                                            

    private void doneButtonMouseClicked(java.awt.event.MouseEvent evt) {                                        
        displayInfo.setVisible(false);
         displayEdit.setVisible(false);
        homePage.setVisible(true);
    }                                       

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {                                        
        homePage.setVisible(false);
        displayInfo.setVisible(false);
        displayEdit.setVisible(true);
    }                                       

    private void helpEditButtonMouseClicked(java.awt.event.MouseEvent evt) {                                            
        new helpEditScreen().setVisible(true);
    }                                           

    private void recycleEditComboActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // SAVE SELECTION TO RECYCLE 
        //set recycleNew as a number 0-12 using the recycleEditCombo
    }                                                

    

    // Variables declaration - do not modify                     
    private javax.swing.JTextField ManufactEditText;
    private javax.swing.JLabel cpuCodeLabel;
    private javax.swing.JPanel displayEdit;
    private javax.swing.JPanel displayInfo;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton enterEditButton;
    private javax.swing.JButton helpEditButton;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel homePageLabel;
    private javax.swing.JTextField itemEditText;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JLabel manufactLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox recycleEditCombo;
    private javax.swing.JTextField recycleEditText;
    private javax.swing.JLabel recycleTypeLabel;
    private javax.swing.JLabel scanEnvyLogo;
    private javax.swing.JTextField upcText;
    private javax.swing.JLabel userInfoPrompt1;
    private javax.swing.JLabel userInfoPromt2;
    // End of variables declaration                   


/*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
*/
}